name: DAST - ZAP Authenticated Full Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticated ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ secrets.TARGET_URL }}
          context: ".zap/login-flask2.context"
          cmd_options: > 
            -n .zap/app.context
            -U zapUser
            -z "auth.loginurl=${{ secrets.TARGET_URL }}/login"
            -z "auth.username=${{ secrets.ZAP_USER }}"
            -z "auth.password=${{ secrets.ZAP_PASS }}"
            -r zap-auth-report.html
            -J zap-auth-report.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-auth-reports
          path: zap-auth-report.*

