name: ZAP Automation Framework scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Automation Framework
        uses: zaproxy/action-af@v0.2.0
        
        env:
          ZAP_USER: ${{ secrets.ZAP_USER }}
          ZAP_PASS: ${{ secrets.ZAP_PASS }}
        with:
          plan: '.zap/plan.yml'
          docker_env_vars: |
            ZAP_USER
            ZAP_PASS

