name: SAST - CodeQL Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 7 * * 1' # skany raz na tydzień

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Initialize CodeQl
        uses: github/codeql-action/init@v3
        with:
          languages: python

# przyda się, jeśli będziemy mieli np. kontenery
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run Analysis
        uses: github/codeql-action/analyze@v3
